#+TITLE: Матан. Подготвка к экзамену.
#+latex_header: \usepackage[utf8x]{inputenc}
#+latex_header: \usepackage[T2A]{fontenc}
#+latex_header: \hypersetup{colorlinks, citecolor=black, filecolor=black, linkcolor=black, urlcolor=black}
* Даты
** Консультация 
/2021-06-24 Thu/
** Экзамен 
/2021-06-25 Fri/

* Видосы 
** Интегралы
[[https://www.youtube.com/watch?v=nCx6FTChgow][Интеграл: Азы интегрирования. Высшая математика]]
[[https://www.youtube.com/watch?v=wEmtlqJy2MM][
Определенный интеграл. Шпаргалка для первокурсника. Высшая математика]]
** Ряды
[[https://www.youtube.com/watch?v=XcofHzGx9Ug][Математический анализ, 35 урок, Числовые ряды]]
[[https://www.youtube.com/watch?v=uq78fpEas5I][
Математический анализ, 36 урок, Достаточные признаки сходимости]]
* Темы
** Первообразная и неопределенный интеграл (определения). Свойства интеграла. Таблица основных неопределенных интегралов. Формула замены переменной в неопределенном интеграле (с доказательством). Формула интегрирования по частям.
*** DONE Опр. 1. 
    CLOSED: [2021-06-19 Sat 02:21]
Функция /F/ называется первообразной функции /f/ на промежутке \Delta , если /F/ дифференцируема на \Delta и в каждой точке /x/ \in \Delta
 \begin{eqnarray}
 F'(x)=f(x)
 \end{eqnarray}
 Очевидно, что первообразная /F(x)/ непрерывна на \Delta.

*** DONE Опр. 2.  
    CLOSED: [2021-06-19 Sat 02:21]
Пусть функция /f(x)/ задана на промежутке \Delta. Совокупность всех ее первообразных на этом промежутке называется /*неопределенным интегралом от функции /f/*/ и обозначается

 \begin{eqnarray}
 \int f(x)dx
 \end{eqnarray}

 Если /F(x)/ — какая-либо первообразная функции /f(x)/ на \Delta, то пишут

 \begin{eqnarray}
 \int f(x)dx=F(x)+C
 \end{eqnarray}

 /C/ — произвольная постоянная.

*** DONE Основные свойства интеграла 
    CLOSED: [2021-06-19 Sat 02:21]

**** Если функция /F(x)/ дифференцируема на \Delta, то

 \begin{eqnarray}
 \int dF(x)=F(x)+C \text{ или }\int F'(x)dx=F(x)+C
 \end{eqnarray}

**** Пусть функция /f(x)/ имеет первообразную на \Delta. Тогда для любого /x/ \in \Delta имеет место равенство:

 \begin{eqnarray}
 d\int f(x)=f(x)dx
 \end{eqnarray}

**** Если функции /f_1/, /f_2/ имеют первообразные на \Delta, то функция /f_1/ + /f_2/ имеет первообразную на \Delta, причем:

 \begin{eqnarray}
 \int(f_1(x) + f_2(x))dx=\int f_1(x)dx + \int f_2(x)dx
 \end{eqnarray}

**** Если функция /f(x)/ имеет первообразную на \Delta, /k/ \in /\R/, то функция /kf(x)/ также имеет на \Delta первообразную, и при /k/ \ne 0:

 \begin{gather*}
 \int kf(x)dx=\{kF(x)+C\}\text{, }k\int f(x)dx=k\{F(x)+C\}
 \end{gather*}

 Т.к. /C/ – произвольная постоянная и /k/ \ne 0, то множества ${kF(x) + C}$ и $k{F(x) + C}$ совпадают.
 
*** DONE След. 1 (Линейность интеграла)
    CLOSED: [2021-06-19 Sat 02:21]
Если f_1 и f_2 имеют первообразные на \Delta, \lambda_1, \lambda_2 \in \R, $\lambda_1^2+\lambda_2^2>0$, 
то функция $\lambda_1 f_1+\lambda_2 f_2$ имеет первообразную на \Delta, причем

  \begin{eqnarray}
  \int(\lambda_1 f_1(x)+\lambda_2 f_2(x))dx=\lambda_1\int f_1(x)dx+\lambda_2\int f_2(x))dx
  \end{eqnarray}

 Доказательство вытекает из свойств 3 и 4.
*** TODO Формула замены переменной
Пусть функции $f(x)$ и $\varphi(t)$ заданы соответственно на промежутках $\Delta_x$ и $\Delta_t$, 
причем $\varphi (\Delta_t) = \Delta_x$, т.е. имеет смысл сложная функция $f(\varphi(t))$, $t \in \Delta_t$. 
Пусть, кроме того, функция $\varphi(t)$ дифференцируема и строго монотонна на $\Delta_t$. Тогда у функции $\varphi(t)$
существует обратная однозначная функция $\varphi^{-1}(x)$, определенная на промежутке $\Delta_x$.

*Теорема 1.* Существование на промежутке $\Delta_x$ интеграла

   \begin{eqnarray}
 \int f(x)dx
   \end{eqnarray}

 и существование на промежутке $\Delta_t$ интеграла

   \begin{eqnarray}
 \int f(\varphi(t))\varphi'(t)dt
   \end{eqnarray}

 равносильны, и имеет место формула

   \begin{eqnarray}
 \int f(x)dx=\int f(\varphi(t))\varphi'(t)dt\bigg|_{t=\varphi^{-1}(x)}
   \end{eqnarray}

 Формула (10) называется формулой замены переменной в неопределенном интеграле:
 переменная x заменяется переменной t по формуле $x = \varphi(t)$.


*Доказательство.* Докажем, что существование первообразной у функции f(x) на
\Delta_x равносильно существованию первообразной у функции $f(\varphi(t))\varphi'(t)$  на \Delta_t
. Пусть у функции f(x) на \Delta_x существует первообразная F(x), т.е.

\begin{eqnarray}
\frac{dF(x)}{dx} = f(x)\text{, } x\in\Delta_t
\end{eqnarray}

Имеет смысл сложная функция F (\varphi(t)), она является первообразной функции $f(varphi(t))\varphi'(t)$ на \Delta_t. 
Действительно,
d
dtF (ϕ(t)) = d F(x)
dx
¯
¯
¯
¯
x=ϕ(t)
d ϕ(t)
dt = f (ϕ(t)) ϕ
0
(t). (14)
Обратно. Пусть функция f (ϕ(t)) ϕ
0
(t) имеет первообразную Φ(t), тогда
d Φ(t)
dt = f (ϕ(t)) ϕ
0
(t). (15)
Покажем, что Φ (ϕ
−1
(x)) является на ∆x первообразной функции f(x). В самом
деле,
d
dxΦ
¡
ϕ
−1
(x)
¢
=
d Φ(t)
dt
¯
¯
¯
¯
t=ϕ−1(x)
d ϕ−1
(x)
dx = (f (ϕ(t)) ϕ
0
(t))|
t=ϕ−1(x) ×
×
dϕ−1
(x)
dx = f(x).
Итак, интегралы (10) и (11) одновременно существуют или нет. При этом
Z
f(x)dx = F(x) + C, (16)
Z
f (ϕ(t)) ϕ
0
(t)dt = F (ϕ(t)) + C,
а так как F (ϕ(t))|
t=ϕ−1(x) = F(x), имеет равенство (12).
** Определенный интеграл Римана (определение). Ограниченность интегрируемых функций (с доказательством). Верхние и нижние суммы Дарбу (определения). Верхний и нижний интегралы Дарбу (определения). Критерий Дарбу. Интегрируемость непрерывных функций. Интегрируемость монотонных функций.

** Свойства определенного интеграла (сформулировать все, доказать непрерывность интеграла по верхнему пределу). Интегральная теорема о среднем.

** Теорема о дифференцировании интеграла по верхнему пределу (с доказательством).  Теорема о существовании первообразной (с доказательством). Формула Ньютона-Лейбница (с доказательством). Формула замены переменной в определенном интеграле. Формула интегрирования по частям.

** Определение несобственных интегралов.  Формула Ньютона-Лейбница и формула замены переменной для несобственных интегралов.

** Несобственные интегралы от неотрицательных функций (лемма и признак сравнения). Критерий Коши сходимости интеграла (с доказательством). Абсолютно сходящиеся интегралы (определение и теорема о сходимости абсолютно сходящегося интеграла).

** Определение числового ряда. Необходимый признак сходимости ряда (с доказательством). Критерий Коши сходимости ряда (с доказательством). Ряды с неотрицательными членами (признак сравнения, интегральный признак Коши, радикальный признак Коши, признак Даламбера).

** Знакопеременные ряды (признак Лейбница). Абсолютно сходящиеся ряды (определение). Критерий Коши абсолютной сходимости ряда. Условно сходящиеся ряды (определение). Теорема Римана.

** Функциональные последовательности  и ряды (определения, в том числе, ограниченная последовательность, сходящаяся последовательность, сходящийся ряд, абсолютно сходящийся ряд). Равномерная сходимость функциональной последовательности и функционального ряда (определение и пример). Критерии Коши равномерной сходимости функциональной последовательности (ряда). Признак Вейерштрасса.

** Свойства равномерно сходящихся рядов (непрерывность суммы (с доказательством), интегрирование, дифференцирование).  

** Степенные ряды (определение). Первая теорема Абеля (с доказательством). Радиус и круг (интервал) сходимости степенного ряда (определения). Понятие аналитической функции (определение). Теорема о представлении аналитической функции рядом Тейлора. 

** Определение n-мерного арифметического евклидова пространства. Определение n-мерного открытого шара. Предел последовательности в n-мерном пространстве, ограниченное множество  в n-мерном пространстве, окрестность бесконечно удалённой точки (определения).

** Внутренняя точка множества, открытое множество, точка прикосновения множества, предельная точка множества, замыкание множества, замкнутое множество, компактное множество, линейно связное множество, выпуклое множество, область (определения).
