#+TITLE: Матан. Подготвка к экзамену.
#+latex_header: \usepackage[utf8x]{inputenc}
#+latex_header: \usepackage[T2A]{fontenc}
#+latex_header: \usepackage[colorlinks=true, linkcolor=Maroon, urlcolor=Maroon]{hyperref}
* Даты
** Консультация 
/2021-06-24 Thu/
** Экзамен 
/2021-06-25 Fri/

* Темы
** Первообразная и неопределенный интеграл (определения). Свойства интеграла. Таблица основных неопределенных интегралов. Формула замены переменной в неопределенном интеграле (с доказательством). Формула интегрирования по частям.

*** Опр. 1. 
Функция /F/ называется первообразной функции /f/ на промежутке \Delta , если /F/ дифференцируема на \Delta и в каждой точке /x/ \in \Delta
\begin{eqnarray}
&&F'(x)=f(x)&&
\end{eqnarray}
Очевидно, что первообразная /F(x)/ непрерывна на \Delta.

*** Опр. 2.  
Пусть функция /f(x)/ задана на промежутке \Delta. Совокупность всех ее первообразных на этом промежутке называется /*неопределенным интегралом от функции /f/*/ и обозначается

\begin{eqnarray}
\int&f(x)&dx
\end{eqnarray}

Если /F(x)/ — какая-либо первообразная функции /f(x)/ на /Delta, то пишут

\begin{eqnarray}
$$\int&f(x)&dx=&F(x)&+C$$
\end{eqnarray}

/C/ — произвольная постоянная.

*** Основные свойства интеграла 

**** Если функция /F(x)/ дифференцируема на \Delta, то

 \begin{eqnarray}
 \int d&F(x)&=&F(x)&+C \text{ или } \int&F'(x)&dx=&F(x)&+C
 \end{eqnarray}

**** Пусть функция /f(x)/ имеет первообразную на \Delta. Тогда для любого /x/ \in \Delta имеет место равенство:

 \begin{eqnarray}
 d\int&f(x)&=&f(x)&dx
 \end{eqnarray}

**** Если функции /f_1/, /f_2/ имеют первообразные на \Delta, то функция /f_1/ + /f_2/ имеет первообразную на \Delta, причем:

 \begin{eqnarray}
 \int(&f_1(x)& + &f_2(x)&)dx=\int&f_1(x)&dx + \int&f_2(x)&dx
 \end{eqnarray}

**** Если функция /f(x)/ имеет первообразную на \Delta, /k/ \in /\R/, то функция /kf(x)/ также имеет на \Delta первообразную, и при /k/ \ne 0:

 \begin{gather*}
 \int k&f(x)&dx=\{k&F(x)&+C\}\text{, }k\int&f(x)&dx=k\{&F(x)&+C\}
 \end{gather*}

 Т.к. /C/ – произвольная постоянная и /k/ \ne 0, то множества {/kF(x)/ + /C/} и /k/{/F(x)/ + /C/} совпадают.


*** След. 1 (Линейность интеграла)
Если f1 и f2 имеют первообразные на ∆ ,
λ1 , λ2 ∈ R , λ
2
1 + λ
2
2 > 0, то функция λ1f1 + λ2f2 имеет первообразную на ∆ , причем
Z
(λ1f1(x) + λ2f2(x))dx = λ1
Z
f1(x)dx + λ2
Z
f2(x)dx. (7)
Доказательство вытекает из свойств 3
o и 4
o
.


** Определенный интеграл Римана (определение). Ограниченность интегрируемых функций (с доказательством). Верхние и нижние суммы Дарбу (определения). Верхний и нижний интегралы Дарбу (определения). Критерий Дарбу. Интегрируемость непрерывных функций. Интегрируемость монотонных функций.

** Свойства определенного интеграла (сформулировать все, доказать непрерывность интеграла по верхнему пределу). Интегральная теорема о среднем.

** Теорема о дифференцировании интеграла по верхнему пределу (с доказательством).  Теорема о существовании первообразной (с доказательством). Формула Ньютона-Лейбница (с доказательством). Формула замены переменной в определенном интеграле. Формула интегрирования по частям.

** Определение несобственных интегралов.  Формула Ньютона-Лейбница и формула замены переменной для несобственных интегралов.

** Несобственные интегралы от неотрицательных функций (лемма и признак сравнения). Критерий Коши сходимости интеграла (с доказательством). Абсолютно сходящиеся интегралы (определение и теорема о сходимости абсолютно сходящегося интеграла).

** Определение числового ряда. Необходимый признак сходимости ряда (с доказательством). Критерий Коши сходимости ряда (с доказательством). Ряды с неотрицательными членами (признак сравнения, интегральный признак Коши, радикальный признак Коши, признак Даламбера).

** Знакопеременные ряды (признак Лейбница). Абсолютно сходящиеся ряды (определение). Критерий Коши абсолютной сходимости ряда. Условно сходящиеся ряды (определение). Теорема Римана.

** Функциональные последовательности  и ряды (определения, в том числе, ограниченная последовательность, сходящаяся последовательность, сходящийся ряд, абсолютно сходящийся ряд). Равномерная сходимость функциональной последовательности и функционального ряда (определение и пример). Критерии Коши равномерной сходимости функциональной последовательности (ряда). Признак Вейерштрасса.

** Свойства равномерно сходящихся рядов (непрерывность суммы (с доказательством), интегрирование, дифференцирование).  

** Степенные ряды (определение). Первая теорема Абеля (с доказательством). Радиус и круг (интервал) сходимости степенного ряда (определения). Понятие аналитической функции (определение). Теорема о представлении аналитической функции рядом Тейлора. 

** Определение n-мерного арифметического евклидова пространства. Определение n-мерного открытого шара. Предел последовательности в n-мерном пространстве, ограниченное множество  в n-мерном пространстве, окрестность бесконечно удалённой точки (определения).

** Внутренняя точка множества, открытое множество, точка прикосновения множества, предельная точка множества, замыкание множества, замкнутое множество, компактное множество, линейно связное множество, выпуклое множество, область (определения).
